jenkins:
  controller:
    admin:
      password: "admin"
      adminPassword: "admin"

    # installPlugins:
    #   - "timestamper:1.30"
    #   - "ws-cleanup:0.49"
    persistence:
      enabled: true