apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.service.name }}-config"
data:
  APP_NAME: "{{ .Values.config.APP_NAME }}"
  APP_VERSION: "{{ .Values.config.APP_VERSION }}"
  DEBUG: "{{ .Values.config.DEBUG }}"
  HOST: "{{ .Values.config.HOST }}"
  PORT: "{{ .Values.service.targetPort }}"