grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:

      - name: Prometheus
        type: prometheus
        isDefault: true
        access: proxy
        url: http://myprom-prometheus-server:80 

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps:
    default: "node-exporter-configmap"

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
